import Navbar from '@/components/navbar/navbar'
import './globals.css';
import {ThemeProvider} from '../context/ThemeContext';
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'lamamia',
  description: 'Generated by lamamia',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`dark ${inter.className}`}>
        <ThemeProvider>
          <div className='container '>
            <Navbar />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
